import React, { useState } from 'react';
import { RefreshCcw, Star, Trophy, Users } from 'lucide-react';
import { createRoot } from 'react-dom/client';

const App = () => {
  const [teamName, setTeamName] = useState('');
  const [playerName, setPlayerName] = useState('');
  const [marketingTopic, setMarketingTopic] = useState('');
  const [generatedContent, setGeneratedContent] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleGenerate = async () => {
    if (!teamName || !playerName || !marketingTopic) {
      setError('Please fill in all fields.');
      return;
    }

    setIsLoading(true);
    setGeneratedContent(null);
    setError(null);

    const systemPrompt = `
      You are an expert sports marketing copywriter. Your task is to generate compelling, professional, and grammatically perfect marketing copy for a football team's social media. The copy should be based on the provided team, player, and topic. You must use the provided search results to incorporate real-world details about the team, especially their stadium. If stadium information is available, weave it into the copy. If not, focus on the player and team.
      
      Your output should be a single, well-structured paragraph that captures the spirit of the team and the excitement of the game. Do not include any title, markdown, or conversational text. Just the marketing copy.
    `;

    const userQuery = `
      Generate marketing content for the following:
      Team: ${teamName}
      Player: ${playerName}
      Topic: ${marketingTopic}

      Please also find information about the team's home stadium to include in the copy.
    `;
    
    // IMPORTANT: Leaving the apiKey blank allows the Canvas environment to automatically provide it.
    const apiKey = "";
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key=${apiKey}`;

    const payload = {
      contents: [{ parts: [{ text: userQuery }] }],
      tools: [{ "google_search": {} }],
      systemInstruction: {
        parts: [{ text: systemPrompt }]
      },
    };

    try {
      const response = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      
      if (!response.ok) {
        throw new Error(`API error: ${response.statusText}`);
      }

      const result = await response.json();
      const candidate = result.candidates?.[0];

      if (candidate && candidate.content?.parts?.[0]?.text) {
        setGeneratedContent(candidate.content.parts[0].text);
      } else {
        throw new Error('No content was generated by the API.');
      }
    } catch (err) {
      console.error("Failed to generate marketing content:", err);
      setError(`Failed to generate content. Please try again. Error: ${err.message}`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 flex items-center justify-center p-4">
      <div className="w-full max-w-3xl bg-white dark:bg-gray-800 rounded-2xl shadow-2xl p-8 space-y-8 transition-colors duration-200">
        <header className="flex flex-col items-center text-center">
          <h1 className="text-4xl font-extrabold text-blue-600 dark:text-blue-400 mb-2">
            Football Marketing Generator
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Create compelling social media copy for your favorite football team.
          </p>
        </header>

        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <label htmlFor="teamName" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Team Name
              </label>
              <input
                type="text"
                id="teamName"
                className="mt-1 block w-full rounded-md border-gray-300 dark:border-gray-600 shadow-sm focus:border-blue-500 focus:ring-blue-500 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100"
                value={teamName}
                onChange={(e) => setTeamName(e.target.value)}
                placeholder="e.g., San Francisco 49ers"
              />
            </div>
            <div>
              <label htmlFor="playerName" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Player Name
              </label>
              <input
                type="text"
                id="playerName"
                className="mt-1 block w-full rounded-md border-gray-300 dark:border-gray-600 shadow-sm focus:border-blue-500 focus:ring-blue-500 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100"
                value={playerName}
                onChange={(e) => setPlayerName(e.target.value)}
                placeholder="e.g., Terrell Turner"
              />
            </div>
            <div>
              <label htmlFor="marketingTopic" className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Marketing Topic
              </label>
              <select
                id="marketingTopic"
                className="mt-1 block w-full rounded-md border-gray-300 dark:border-gray-600 shadow-sm focus:border-blue-500 focus:ring-blue-500 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-100"
                value={marketingTopic}
                onChange={(e) => setMarketingTopic(e.target.value)}
              >
                <option value="">Select a topic</option>
                <option value="Game Day Hype">Game Day Hype</option>
                <option value="Player Spotlight">Player Spotlight</option>
                <option value="Off-Season Training">Off-Season Training</option>
                <option value="Community Engagement">Community Engagement</option>
              </select>
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={isLoading}
            className="w-full flex justify-center items-center px-6 py-3 border border-transparent text-base font-medium rounded-lg shadow-sm text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:bg-gray-400 dark:disabled:bg-gray-600 transition-colors duration-200"
          >
            {isLoading ? (
              <>
                <RefreshCcw className="animate-spin mr-2" />
                Generating...
              </>
            ) : (
              'Generate Marketing Copy'
            )}
          </button>
        </div>

        {error && (
          <div className="bg-red-100 dark:bg-red-900 border-l-4 border-red-500 text-red-700 dark:text-red-300 p-4 rounded-lg" role="alert">
            <p className="font-bold">Error</p>
            <p>{error}</p>
          </div>
        )}

        {generatedContent && (
          <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-6 shadow-inner border border-gray-200 dark:border-gray-600">
            <h2 className="text-xl font-bold mb-4 text-gray-800 dark:text-gray-200 flex items-center">
              <Star className="mr-2 text-yellow-500" />
              Generated Content
            </h2>
            <div className="prose dark:prose-invert">
              <p className="text-lg text-gray-800 dark:text-gray-200">{generatedContent}</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default App;
