version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mount backend code for live reload (development)
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-dev_drillbot_db}
      - DB_USER=${DB_USER:-delta_drill}
      - DB_PASSWORD=${DB_PASSWORD:-FetVulture@78_2407} # Note: Use .env file for secrets
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:8080" # Vite default port, adjust if necessary
    volumes:
      - ./frontend:/app # Mount frontend code for live reload (development)
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-dev_drillbot_db}
      POSTGRES_USER: ${DB_USER:-delta_drill}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-FetVulture@78_2407} # Note: Use .env file for secrets

volumes:
  postgres_data:
